name: Autograding

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install required system dependencies (e.g., for Tkinter or others)
      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      # Install Python dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run the tests
      - name: Run Tests
        run: |
          python -m pytest battleship_test.py --tb=short
