name: Autograding Tests

'on':
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install pytest coverage pytest-json-report

      - name: Run Test Cases
        id: run-tests
        run: |
          coverage run -m pytest battleship_test.py --tb=short --json-report --json-report-file=test_results.json
          coverage report -m
        continue-on-error: true  

      - name: Compute Grade and Percentage
        id: compute-grade
        run: |
          echo "Debug: Calculating grade"
          score_value=85  # Example value, replace with your actual computation
          total_value=100  # Example value, replace with your actual computation
          echo "::set-output name=SCORE::${score_value}"
          echo "::set-output name=TOTAL::${total_value}"
          echo "SCORE=${score_value}, TOTAL=${total_value}"  # Debugging line
          ${{ steps.compute-grade.outputs.SCORE }}
          ${{ steps.compute-grade.outputs.TOTAL }}


          # python grade_calculator.py test_results.json
          # if [[ -f grade_output.txt ]]; then
          #   cat grade_output.txt  # Debugging: Check file contents
          #   while IFS='=' read -r key value; do
          #     echo "$key=$value" >> $GITHUB_ENV
          #     echo "$key=$value" >> $GITHUB_OUTPUT
          #   done < grade_output.txt
          # else
          #   echo "ERROR: grade_output.txt not found!" >&2
          #   exit 1  # Fail the workflow if the file is missing
          # fi

      - name: Debug Compute Grade Outputs
        run: echo "SCORE=${{ steps.compute-grade.outputs.SCORE }}, TOTAL=${{ steps.compute-grade.outputs.TOTAL }}"
      - name: Print Results
        run: |
          echo "Final Score: ${{ steps.compute-grade.outputs.SCORE }}/ ${{ steps.compute-grade.outputs.TOTAL }}"

      - name: Report Grades to GitHub Classroom
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: "run-tests"  # FIX: This should be the test step, NOT compute-grade
        env:
          SCORE: ${{ steps.compute-grade.outputs.SCORE }}
          TOTAL: ${{ steps.compute-grade.outputs.TOTAL }}
