name: Autograding Tests
'on':
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install pytest coverage pytest-json-report

      - name: Run Test Cases
        id: run-tests
        run: |
          coverage run -m pytest battleship_test.py --tb=short --json-report --json-report-file=test_results.json
          coverage report -m
        continue-on-error: true

      - name: Compute Grade
        id: compute-grade
        run: |
          GRADE=$(python grade_calculator.py test_results.json | grep "Grade=" | cut -d'=' -f2)
          echo "::set-output name=result::$GRADE"

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          FINAL_GRADE: "${{ steps.compute-grade.outputs.result }}"
