name: Autograding Tests

'on':
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install pytest coverage pytest-json-report

      - name: Run Test Cases
        id: run-tests
        run: |
          coverage run -m pytest battleship_test.py --tb=short --json-report --json-report-file=test_results.json
          coverage report -m
        continue-on-error: true  

      - name: Compute Grade and Percentage
        id: compute-grade
        run: |
          python grade_calculator.py test_results.json
          SCORE=$(cat grade_output.txt | grep "Points=" | cut -d'=' -f2)
          TOTAL=$(cat grade_output.txt | grep "TotalPoints=" | cut -d'=' -f2)
          echo "SCORE=$SCORE" >> $GITHUB_ENV
          echo "TOTAL=$TOTAL" >> $GITHUB_ENV
          echo "SCORE=$SCORE" >> $GITHUB_OUTPUT
          echo "TOTAL=$TOTAL" >> $GITHUB_OUTPUT

      - name: Print Results
        run: |
          echo "Final Score: ${{ steps.compute-grade.outputs.SCORE }}/ ${{ steps.compute-grade.outputs.TOTAL }}"

      - name: Report Grades to GitHub Classroom
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: "compute-grade"
        env:
          SCORE: ${{ steps.compute-grade.outputs.SCORE }}
          TOTAL: ${{ steps.compute-grade.outputs.TOTAL }}
