name: Autograding Tests

'on':
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install pytest coverage pytest-json-report

      - name: Run Test Cases
        id: run-tests
        run: |
          coverage run -m pytest battleship_test.py --tb=short --json-report --json-report-file=test_results.json
          coverage report -m
        continue-on-error: true  

      - name: Compute Grade and Percentage
        id: compute-grade
        run: |
          python grade_calculator.py test_results.json
          PERCENTAGE=$(cat grade_output.txt | grep "Percentage=" | cut -d'=' -f2)
          GRADE=$(cat grade_output.txt | grep "Grade=" | cut -d'=' -f2)
          echo "FINAL_PERCENTAGE=$PERCENTAGE" >> $GITHUB_ENV
          echo "FINAL_GRADE=$GRADE" >> $GITHUB_ENV
          echo "FINAL_PERCENTAGE=$PERCENTAGE" >> $GITHUB_OUTPUT
          echo "FINAL_GRADE=$GRADE" >> $GITHUB_OUTPUT

      - name: Print Results
        run: |
          echo "Final Percentage: ${{ steps.compute-grade.outputs.FINAL_PERCENTAGE }}%"
          echo "Final Grade: ${{ steps.compute-grade.outputs.FINAL_GRADE }}"

      # - name: Report Grades to GitHub Classroom
      #   uses: classroom-resources/autograding-grading-reporter@v1
      #   with:
      #     runners: "run-autograding-tests"  # Required field (string, not array)
      #   env:
      #     # FINAL_GRADE: ${{ steps.compute-grade.outputs.FINAL_GRADE }}
      #     FINAL_PERCENTAGE:  ${{ steps.compute-grade.outputs.FINAL_PERCENTAGE }}%
