name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Install System Dependencies
      run: sudo apt-get update && sudo apt-get install -y python3-tk
    - name: Checkout code
      uses: actions/checkout@v4
    - name: TestCase1
      id: testcase1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: TestCase1
        setup-command: pip install pytest
        command: python -m pytest battleship_test.py
        timeout: 3
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTCASE1_RESULTS: "${{steps.testcase1.outputs.result}}"
      with:
        runners: testcase1
